### ISSUE TITLE
Testing: Extract Metadata

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ExtractMetadata#1]
This module extracts embedded metadata from files and sets them to the media. When creating an item, add multiple media using the Upload or URL option. After adding the item, if the file formats are supported, you will likely see extracted metadata assigned to the respective media. (Check the README for supported file formats.) Note that not all files have embedded metadata, so a lack of metadata is not necessarily a sign of a bug.

Once you've added several media and their metadata, test the "Extract metadata" tab on the item _and_ media edit pages. You should see an option to refresh or clear the metadata. Test that clearing metadata does indeed delete the metadata from the media. Test that refreshing the metadata does indeed add the metadata back in. Also, test the "Extract metadata" option on the item _and_ media batch edit forms. Note that clearing and refreshing metadata on an item should clear or refresh _all_ the item's child media.

An equally important part of this is testing as many file formats as possible. The current list of supported file formats and metadata is not exhaustive, so I would like to know which formats you would like to see supported that are not currently. Also, if you feel that a file should have metadata but doesn't, bring it to my attention.

**Comment by katknow** [comment]
@jimsafley I'm getting this when I try to install the plugin: 

 ParseError
syntax error, unexpected ')'

Details:

ParseError: syntax error, unexpected ')' in /var/www/html/katknow/OmekaSTesting/modules/ExtractMetadata/Module.php:134
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-loader/src/ModuleAutoloader.php(206): Laminas\Loader\ModuleAutoloader->loadModuleFromDir('/var/www/html/k...', 'ExtractMetadata...')
#1 [internal function]: Laminas\Loader\ModuleAutoloader->autoload('ExtractMetadata...')
#2 /var/www/html/katknow/OmekaSTesting/application/src/Module/Manager.php(368): spl_autoload_call('ExtractMetadata...')
#3 /var/www/html/katknow/OmekaSTesting/application/src/Module/Manager.php(239): Omeka\Module\Manager->getModuleObject(Object(Omeka\Module\Module))
#4 /var/www/html/katknow/OmekaSTesting/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module))
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ModuleController->installAction()
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(105): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#10 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#12 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#14 {main}

I tried re-cloning to same results and when I pull it says it's up-to-date...is there something else I need to be doing? Thanks!

**Comment by jimsafley** [comment]
I just made a change that should fix the bug.

**Comment by katknow** [comment]
That did it! Thank you

**Comment by katknow** [comment]
I was having trouble getting this to work so I visited the ReadMe and saw you need something called exiftool? I clicked the link and saw it involved downloading and using Terminal but I'm having trouble getting it to download. Do you have any suggestions? Sorry, I don't have much experience with embedded metadata!

**Comment by sharonmleon** [comment]
Katie, I think that exiftool is the extractor that the module is using. I'm pretty sure we can make files with embedded metadata using photoshop. I'll give that a try tomorrow morning and share some with you.

**Comment by jimsafley** [comment]
On what operating system do you have Omeka installed? Is it a Linux distribution? You probably don't have to download and install exiftool by hand. You could just use your OS's package manager. For example, for Ubuntu just open the terminal and run the command:

`sudo apt-get install libimage-exiftool-perl`

Every OS/distribution has a package manager that makes installing libraries like this easy.

**Comment by katknow** [comment]
Thanks, @sharonmleon. @jimsafley I don't know the specifics of the install, just that it's on the dev server. I've tried accessing it both from mac and windows. I was asking about exiftool because when I was trouble with figuring out the plugin I went back to the config and it says this at the top, so wondered if that was my problem: 

![Screenshot 2021-09-21 at 22-15-08 Configure · Extract Metadata · Modules · Katie's Omeka S Testing Site](https://user-images.githubusercontent.com/84726696/134273185-acfd7f94-90cc-40d7-986f-f28f53d9428d.png)

**Comment by zerocrates** [comment]
It should be there now.

**Comment by katknow** [comment]
This definitely works for pdfs and pngs, currently scrounging up some other file types to play with. Worked on item and media individual pages as well as via bulk edit.

**Comment by jimsafley** [comment]
Great to hear it's working so far! But hold off on testing for now. I've made some _major_ changes that will eventually require another round of testing. For now, **do not** pull in the changes, uninstall the module, and delete the "Extracted Metadata" vocabulary. I'll contact you once I'm ready.

**Comment by jimsafley** [comment]
@katknow I've updated the module. If you haven't already, please uninstall the module and delete the "Extracted Metadata" vocabulary. You can then reinstall it. See the [README](https://github.com/omeka-s-modules/ExtractMetadata#readme) for a list of features to test.

**Comment by katknow** [comment]
@jimsafley it appears I've somehow managed to re-install the module incorrectly--when I go to dev.omeka.org/katknow/OmekaSTesting I now get this message: 

Warning: require_once(/var/www/html/katknow/OmekaSTesting/modules/ExtractMetadata/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/katknow/OmekaSTesting/modules/ExtractMetadata/Module.php on line 29

Fatal error: require_once(): Failed opening required '/var/www/html/katknow/OmekaSTesting/modules/ExtractMetadata/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/katknow/OmekaSTesting/modules/ExtractMetadata/Module.php on line 29

Do you have any suggestions on where I might've gone wrong? Thanks!

**Comment by jimsafley** [comment]
We ran `composer update` in the ExtractMetadata directory. It should be working now.

**Comment by katknow** [comment]
The site works for me now, but regardless of whatever the configuration settings are I consistently get this error:

 Doctrine\DBAL\Exception\TableNotFoundException
An exception occurred while executing 'SELECT t0.id AS id_1, t0.extracted AS extracted_2, t0.extractor AS extractor_3, t0.metadata AS metadata_4, t0.media_id AS media_id_5 FROM extract_metadata t0 WHERE t0.media_id = ?' with params [13603]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'katknow.extract_metadata' doesn't exist

Details:

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'katknow.extract_metadata' doesn't exist in /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(112): PDOStatement->execute(NULL)
#1 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1292): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(903): Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS...', Array, Array)
#3 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(195): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadAll(Array, NULL, NULL, NULL)
#4 /var/www/html/katknow/OmekaSTesting/modules/ExtractMetadata/Module.php(248): Doctrine\ORM\EntityRepository->findBy(Array)
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): ExtractMetadata\Module->ExtractMetadata\{closure}(Object(Laminas\EventManager\Event))
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\EventManager\Event))
#7 /var/www/html/katknow/OmekaSTesting/application/src/View/Helper/Trigger.php(60): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\EventManager\Event))
#8 [internal function]: Omeka\View\Helper\Trigger->__invoke('view.show.after')
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Omeka\View\Helper\Trigger), Array)
#10 /var/www/html/katknow/OmekaSTesting/application/view/omeka/admin/media/show.phtml(86): Laminas\View\Renderer\PhpRenderer->__call('trigger', Array)
#11 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
#12 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#13 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#14 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#15 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#16 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#17 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#18 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#19 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#20 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#21 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'katknow.extract_metadata' doesn't exist in /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(114): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1292): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(903): Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS...', Array, Array)
#3 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(195): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadAll(Array, NULL, NULL, NULL)
#4 /var/www/html/katknow/OmekaSTesting/modules/ExtractMetadata/Module.php(248): Doctrine\ORM\EntityRepository->findBy(Array)
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): ExtractMetadata\Module->ExtractMetadata\{closure}(Object(Laminas\EventManager\Event))
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\EventManager\Event))
#7 /var/www/html/katknow/OmekaSTesting/application/src/View/Helper/Trigger.php(60): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\EventManager\Event))
#8 [internal function]: Omeka\View\Helper\Trigger->__invoke('view.show.after')
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Omeka\View\Helper\Trigger), Array)
#10 /var/www/html/katknow/OmekaSTesting/application/view/omeka/admin/media/show.phtml(86): Laminas\View\Renderer\PhpRenderer->__call('trigger', Array)
#11 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
#12 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#13 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#14 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#15 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#16 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#17 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#18 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#19 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#20 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#21 {main}

Next Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.extracted AS extracted_2, t0.extractor AS extractor_3, t0.metadata AS metadata_4, t0.media_id AS media_id_5 FROM extract_metadata t0 WHERE t0.media_id = ?' with params [13603]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'katknow.extract_metadata' doesn't exist in /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:61
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDO\Exception))
#1 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'An exception oc...')
#2 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2214): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT t0.id AS...', Array)
#3 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1304): Doctrine\DBAL\Connection->handleExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT t0.id AS...', Array, Array)
#4 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(903): Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS...', Array, Array)
#5 /var/www/html/katknow/OmekaSTesting/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(195): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadAll(Array, NULL, NULL, NULL)
#6 /var/www/html/katknow/OmekaSTesting/modules/ExtractMetadata/Module.php(248): Doctrine\ORM\EntityRepository->findBy(Array)
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): ExtractMetadata\Module->ExtractMetadata\{closure}(Object(Laminas\EventManager\Event))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\EventManager\Event))
#9 /var/www/html/katknow/OmekaSTesting/application/src/View/Helper/Trigger.php(60): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\EventManager\Event))
#10 [internal function]: Omeka\View\Helper\Trigger->__invoke('view.show.after')
#11 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Omeka\View\Helper\Trigger), Array)
#12 /var/www/html/katknow/OmekaSTesting/application/view/omeka/admin/media/show.phtml(86): Laminas\View\Renderer\PhpRenderer->__call('trigger', Array)
#13 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
#14 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#15 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#16 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#17 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#18 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#19 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#20 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#21 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#22 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#23 {main}

However, the extract metadata tab and icons are still visible.

**Comment by jimsafley** [comment]
Try this: go to the modules page, find the ExtractMetadata module, click "Uninstall", then click "Install."

**Comment by katknow** [comment]
That did it! Sorry, didn't even occur to me to uninstall & reinstall since I had just reinstalled it. Thank you!

**Comment by katknow** [comment]
Quick question -- should I be able to see anything on the "Extract Metadata" when I'm not on the editing page? Just curious because the tab is still visible, but when you click through it's blank.

**Comment by jimsafley** [comment]
Good catch. That tab and section should not be visible when the media has no metadata. I've made a change to the code. Pull and try it out.

**Comment by katknow** [comment]
Still looking for some more obscure file types with extractable metadata to test, but overall it seems to be working. I think it may need some pretty detailed documentation. Works on both the item page and media page, although it is rendered differently on both. To verify, the extract metadata function on the item page is essentially just linking to the information on the media page? 

I don't know if this has to do with my specific configuration/set-up, but on config page it says I do not have access to Tika, so that's not something I can test. I have ExifTool, getID3, and exif all checked, but so far I've only managed to get ExifTool and getID3 on extract metadata tab so I'm trying to find something to test exif.

When using the batch edit function, you are able to refresh and delete extracted metadata via the "edit selected" option. However, it seems that you cannot do it via the "edit all" option, although I don't know if this may have to do with the number of items (I have over 6,000 in my test site).

I'm not sure I fully understand the JSONPointer mapping, but I'm still trying to figure it out. On the JSON Pointer crosswalk on the configuration page, the field for pointer is overlapping with the select property drop down so that may  need to be adjusted. Understandably, it throws an error when you enable mapping without adding pointers. However, when you configure the page you can get a successful configuration message after enabling mapping without adding pointers. I wonder if it would be worth including a message at this stage (even though it says so in the README) so people know they can't just select it without going on to that next step.

**Comment by jimsafley** [comment]
> To verify, the extract metadata function on the item page is essentially just linking to the information on the media page?

The extract metadata function on the item page will perform the selected action on _every_ media assigned to that item.

> I do not have access to Tika, so that's not something I can test.

Yes, Tika requires a dependency that most users won't have. I've included it more as an example of the breadth of extractors that is possible.

> I'm trying to find something to test exif.

I'm surprised that Exif isn't working when it says it's available. It should extract metadata from just about any JPEG or TIFF file. Have you tried those types?

> However, it seems that you cannot do it via the "edit all" option,

That's strange. I see the "Extract metadata" field on the batch edit all pages (item and media). You should see it regardless of the number of items. Can you confirm?

> the field for pointer is overlapping with the select property drop down

Could you post a screen shot? I had the same issue but I fixed it.

> Understandably, it throws an error when you enable mapping without adding pointers

Does it? It's not on my installation. What's the error?

**Comment by jimsafley** [comment]
Also, make sure to pull in the recent changes.

**Comment by katknow** [comment]
> I'm surprised that Exif isn't working when it says it's available. It should extract metadata from just about any JPEG or TIFF file. Have you tried those types?

I've tried a JPEG, but I'll find a different one to make sure that it's not an issue with this specific file.

> That's strange. I see the "Extract metadata" field on the batch edit all pages (item and media). You should see it regardless of the number of items. Can you confirm?

It says I have the option, but it doesn't actually let me execute the action like it does when you use the check boxes. I just tried to batch "delete metadata," and nothing happened. Could very possibly be user error on my part, but don't know why I could get it to work on one and not the other since I'm working from the same page in both options.

> Could you post a screen shot? I had the same issue but I fixed it.

I think it might be a FireFox specific view--just double checked on Chrome and Safari and is working fine there now. Cleared cache & hard refreshed in FireFox and nothing changed. However, it doesn't interfere with visibility of content within the field so I don't know if it really matters:

<img width="1160" alt="Screen Shot 2021-10-12 at 12 24 18 PM" src="https://user-images.githubusercontent.com/84726696/136995551-1fd3d05a-9502-4ea4-a535-4b29ef505e74.png">

> Does it? It's not on my installation. What's the error?

This recent pull seems to have fixed it. I had pulled Sunday and got the "your branch is up to date" message, so don't know why it would be different.  However, it is also very possible I just got confused in git again.

**Comment by jimsafley** [comment]
About the batch edit all issue: that process happens in the background so you will not see immediate results. Go to your "Jobs" page and look for jobs with the class of "Omeka\Job\BatchUpdate". They should all have a status of "Completed". If you see a status of "Starting" then the process never began. If you see a status of "In progress" then the process is either hanging or not completed yet. Given that you have around 6000 items, I imagine that the process can take a while.

**Comment by katknow** [comment]
Thanks! It did complete eventually, it just took a while.

**Comment by katknow** [comment]
I downloaded Adobe Bridge and added some metadata to jpegs, and am finally getting it to register all three: Exif,ExifTool, and getID3.

I'm now going down the list and testing the various file types, but it's taking a bit because I'm finding free files on the internet then adding dummy metadata myself in Bridge if it's not bringing anything up. So far--

- aiff: data extracted via ExifTool
- app14: still looking for something to test
- asf: I've tried five different ones, get the message "Cannot store files with the media type 'video/x-ms-asf'" every time so don't know if I'm just not finding good free files
- exe: getting the message "Cannot store files with the media type "application/x-dosexec"", looking for alternate files to test that pass my anti-virus scan
- exif: data extracted via exif, ExifTool, and getID3
- flac: getting the messages "Cannot store files with the media type "audio/x-flac"." and "Cannot store files with the resolved extension "flac"." - looking for alternative test files
- fpx: having a hard time finding a free one to download and test
- gif: data extracted via ExifTool and getID3

- ICC Profile: data extracted via exif, ExifTool, and getID3
- ID3: data extracted via ExifTool and get ID3
- IPTC IIM: data extracted via exif, ExifTool, and getID3
- mpeg: data extracted via ExifTool and getID3
- pdf: data extracted via ExifTool and getID3
- Photoshop IRB: still looking for something to test
- png: data extracted via ExifTool and getID3
- Quicktime: data extracted via ExifTool and getID3
- riff: need to find a free file to test
- rtf: data extracted via ExifTool
- svg: getting the messages "Cannot store files with the media type "image/svg+xml"." and "Cannot store files with the resolved extension "svg"." - looking for alternative test files
- Vorbis: data extracted via ExifTool
- xml: getting the messages "Cannot store files with the media type "text/xml"." and "Cannot store files with the resolved extension "xml"." - looking for alternative test files
- xmp: need to find a file to test
- zip: data extracted via ExifTool and getID3

**Comment by jimsafley** [comment]
To prevent the "Cannot store files" error, go to Settings > Security and check "Disable file validation". Even so, there's no need to test any more files. You have gone above and beyond! If you've confirmed that everything works as described in the README, I think we can close this issue.

**Comment by katknow** [comment]
Everything does seem to work, including JSON Pointer!
