### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by anders-naslund** [omeka-s-modules/ExtractMetadata#3]
After installing this module the Omeka Admin site is no longer accessible and it only shows this error message:

Warning: require_once(/var/www/utv3.kulturhotell.se/web/modules/ExtractMetadata/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/utv3.kulturhotell.se/web/modules/ExtractMetadata/Module.php on line 29

Fatal error: require_once(): Failed opening required '/var/www/utv3.kulturhotell.se/web/modules/ExtractMetadata/vendor/autoload.php' (include_path='.:') in /var/www/utv3.kulturhotell.se/web/modules/ExtractMetadata/Module.php on line 29

Looking at the module code it looks like to vendor folder and it's files are missing. 
Is this something you could look into?

Adjusting the path to "vendor/autload.php" on line 29 resolved the issue.

**Comment by jimsafley** [comment]
How did you install the module? I expect this to happen if you cloned the repository and did not run `$ composer install`. I recommend that you install the module using the [ZIP](https://github.com/omeka-s-modules/ExtractMetadata/releases/download/v1.0.0/ExtractMetadata-1.0.0.zip), which includes all dependencies.

**Comment by anders-naslund** [comment]
Downloaded the zip, extracted and renamed the folder according to the instructions

**Comment by anders-naslund** [comment]
The issue is resolved by changing line 29 in Module.php from:
     require_once sprintf('%s/vendor/autoload.php', __DIR__);
to:
     require_once sprintf('%s/../../vendor/autoload.php', __DIR__);

**Comment by jimsafley** [comment]
If you install the module from the provided ZIP file there should be no need to change the vendor path.

**Comment by anders-naslund** [comment]
Understood, but that was exactly what I did and I still needed to adjust the vendor path ... anyway it's working now and I know how to do it in future if the source is not fixed :-)
