### ISSUE TITLE
Documentation: Add more mappers

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/ExtractMetadata#5]
Re: https://github.com/omeka/omeka-s-enduser/pull/129#discussion_r929200592

https://omeka.org/s/docs/user-manual/modules/extractmetadata/#mappers

> Mappers map extracted metadata to resource values. Note that a mapper must be enabled on the module configuration page. This module comes with one mapper, but more can be added depending on your need.

How does a user add more mappers? Can we put an example here?

**Comment by jimsafley** [comment]
Adding mappers is highly technical, so it would not be appropriate to include in end-user documentation. In such circumstances, developers would create their own in a separate module, using the existing mapper as an example.
